spring.datasource.url=jdbc:postgresql://db:5432/reservations
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=mySuperSecretKeyForJwtSigningThatIsVeryLongAndSecureEnoughForThisApplication
jwt.expiration=86400000
